import type { User } from "./types.ts";

const fakeUsers: User[] = [
    {
      userId: 1,
      firstName: "Anna",
      secondName: null,
      lastName: "Kowalska",
      email: "anna.kowalska@example.com",
      contactNumber: 48123456789,
      userType: "CUSTOMER",
      isEnabled: true,
      createdAt: "2026-01-02",
    },
    {
      userId: 2,
      firstName: "Piotr",
      secondName: "Jan",
      lastName: "Nowak",
      email: "piotr.nowak@example.com",
      contactNumber: null,
      userType: "CUSTOMER",
      isEnabled: true,
      createdAt: "2026-01-05",
    },
    {
      userId: 3,
      firstName: "Vasil",
      secondName: null,
      lastName: "Vushau",
      email: "vasil@example.com",
      contactNumber: 48500111222,
      userType: "ADMIN",
      isEnabled: true,
      createdAt: "2026-01-10",
    },
    {
      userId: 4,
      firstName: "Ola",
      secondName: null,
      lastName: "Zielinska",
      email: "ola.zielinska@example.com",
      contactNumber: 48777111222,
      userType: "CUSTOMER",
      isEnabled: false,
      createdAt: "2025-12-20",
    },
    {
      userId: 5,
      firstName: "Mateusz",
      secondName: null,
      lastName: "Kaczmarek",
      email: "mateusz.k@example.com",
      contactNumber: 48666111222,
      userType: "CUSTOMER",
      isEnabled: true,
      createdAt: "2026-01-14",
    },
    {
      userId: 6,
      firstName: "Kasia",
      secondName: "Maria",
      lastName: "Lewandowska",
      email: "kasia.lew@example.com",
      contactNumber: null,
      userType: "ADMIN",
      isEnabled: true,
      createdAt: "2026-01-16",
    },
    {
      userId: 7,
      firstName: "Tomasz",
      secondName: null,
      lastName: "Wrobel",
      email: "twrobel@example.com",
      contactNumber: 48555111222,
      userType: "CUSTOMER",
      isEnabled: true,
      createdAt: "2026-01-17",
    },
  ];

export { fakeUsers };