management:
  endpoints:
    web:
      cors:
        allowed-origins: ${cors_origins:http://localhost:8080,http://localhost:5000,http://localhost:5173}
        allowed-headers: ${cors_headers:*}
        allowed-methods: ${cors_methods:*}
        allowed-origin-patterns: ${cors_origin_patterns:/**}