spring:
  datasource:
    hikari:
      data-source-properties:
        useConfigs: maxPerformance
# Jdbc groups several sql insert query statements into single insert query and executes it
# instead of running each sql query. So that number of round trips to the DB will be reduced.
# works well for insert queries but not for update queries.
# https://javabydeveloper.com/spring-jdbctemplate-batch-update-with-maxperformance/#2-3-optimizing-performance
        rewriteBatchedStatements: true